### PR TITLE
Naive attempt to fix #58

### LINKED ISSUE #58: Using outdated and insecure faker
Currently `django-fakery` uses `Faker = ">=2.0,<2.1"`
It is reported as insecure by `safety`: 

```
» safety check --bare --full-report
faker
```

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by sobolevn** [comment]
@fcurella I have removed python2 support and added new `faker` version.

I would love to have this released as soon as possible! 🙏 
I would own you a beer / tea 🍻

**Comment by sobolevn** [comment]
@fcurella friendly ping! 👍

**Comment by fcurella** [comment]
@sobolevn Sorry, I've been super busy lately. Releasing now.

Thank you so much for your work!

**Comment by sobolevn** [comment]
Glad to help. This project saved me so much time!

**Pull request merged**
